name-template: 'Release v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    semver-increment: minor
    when:
      labels:
        - 'feature'
        - 'enhancement'
  - title: '🐛 Fixes'
    semver-increment: patch
    when:
      labels:
        - 'fix'
        - 'bug'
  - title: '🧰 Maintenance'
    semver-increment: patch
    when:
      labels:
        - 'chore'
        - 'dependencies'
  - type: version-resolver
    semver-increment: major
    when:
      label: 'major'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  default: patch

template: |
  ## Änderungen

  $CHANGES
